build a 4D array (batch, height, width, channels), reshape it, transpose axes, flatten it back.

In [51]:
import numpy as np

In [52]:
arr = np.arange(8*4*8*1).reshape(8,4,8,1)
print(arr.shape, arr.ndim, arr.dtype, arr.size)


(8, 4, 8, 1) 4 int64 256


In [53]:
arr = arr.transpose(3, 1, 2, 0)
print(arr.shape, arr.ndim, arr.dtype, arr.size)

(1, 4, 8, 8) 4 int64 256


In [54]:
arr.flags['C_CONTIGUOUS'] 

False

In [55]:
arr = arr.ravel()
print(arr.shape, arr.ndim, arr.dtype, arr.size)

(256,) 1 int64 256


In [56]:
arr.strides 

(8,)

In [57]:
arr

array([  0,  32,  64,  96, 128, 160, 192, 224,   1,  33,  65,  97, 129,
       161, 193, 225,   2,  34,  66,  98, 130, 162, 194, 226,   3,  35,
        67,  99, 131, 163, 195, 227,   4,  36,  68, 100, 132, 164, 196,
       228,   5,  37,  69, 101, 133, 165, 197, 229,   6,  38,  70, 102,
       134, 166, 198, 230,   7,  39,  71, 103, 135, 167, 199, 231,   8,
        40,  72, 104, 136, 168, 200, 232,   9,  41,  73, 105, 137, 169,
       201, 233,  10,  42,  74, 106, 138, 170, 202, 234,  11,  43,  75,
       107, 139, 171, 203, 235,  12,  44,  76, 108, 140, 172, 204, 236,
        13,  45,  77, 109, 141, 173, 205, 237,  14,  46,  78, 110, 142,
       174, 206, 238,  15,  47,  79, 111, 143, 175, 207, 239,  16,  48,
        80, 112, 144, 176, 208, 240,  17,  49,  81, 113, 145, 177, 209,
       241,  18,  50,  82, 114, 146, 178, 210, 242,  19,  51,  83, 115,
       147, 179, 211, 243,  20,  52,  84, 116, 148, 180, 212, 244,  21,
        53,  85, 117, 149, 181, 213, 245,  22,  54,  86, 118, 15

In [58]:
arr[:]

array([  0,  32,  64,  96, 128, 160, 192, 224,   1,  33,  65,  97, 129,
       161, 193, 225,   2,  34,  66,  98, 130, 162, 194, 226,   3,  35,
        67,  99, 131, 163, 195, 227,   4,  36,  68, 100, 132, 164, 196,
       228,   5,  37,  69, 101, 133, 165, 197, 229,   6,  38,  70, 102,
       134, 166, 198, 230,   7,  39,  71, 103, 135, 167, 199, 231,   8,
        40,  72, 104, 136, 168, 200, 232,   9,  41,  73, 105, 137, 169,
       201, 233,  10,  42,  74, 106, 138, 170, 202, 234,  11,  43,  75,
       107, 139, 171, 203, 235,  12,  44,  76, 108, 140, 172, 204, 236,
        13,  45,  77, 109, 141, 173, 205, 237,  14,  46,  78, 110, 142,
       174, 206, 238,  15,  47,  79, 111, 143, 175, 207, 239,  16,  48,
        80, 112, 144, 176, 208, 240,  17,  49,  81, 113, 145, 177, 209,
       241,  18,  50,  82, 114, 146, 178, 210, 242,  19,  51,  83, 115,
       147, 179, 211, 243,  20,  52,  84, 116, 148, 180, 212, 244,  21,
        53,  85, 117, 149, 181, 213, 245,  22,  54,  86, 118, 15

In [59]:
arr[1:]

array([ 32,  64,  96, 128, 160, 192, 224,   1,  33,  65,  97, 129, 161,
       193, 225,   2,  34,  66,  98, 130, 162, 194, 226,   3,  35,  67,
        99, 131, 163, 195, 227,   4,  36,  68, 100, 132, 164, 196, 228,
         5,  37,  69, 101, 133, 165, 197, 229,   6,  38,  70, 102, 134,
       166, 198, 230,   7,  39,  71, 103, 135, 167, 199, 231,   8,  40,
        72, 104, 136, 168, 200, 232,   9,  41,  73, 105, 137, 169, 201,
       233,  10,  42,  74, 106, 138, 170, 202, 234,  11,  43,  75, 107,
       139, 171, 203, 235,  12,  44,  76, 108, 140, 172, 204, 236,  13,
        45,  77, 109, 141, 173, 205, 237,  14,  46,  78, 110, 142, 174,
       206, 238,  15,  47,  79, 111, 143, 175, 207, 239,  16,  48,  80,
       112, 144, 176, 208, 240,  17,  49,  81, 113, 145, 177, 209, 241,
        18,  50,  82, 114, 146, 178, 210, 242,  19,  51,  83, 115, 147,
       179, 211, 243,  20,  52,  84, 116, 148, 180, 212, 244,  21,  53,
        85, 117, 149, 181, 213, 245,  22,  54,  86, 118, 150, 18

In [60]:
arr[:4]

array([ 0, 32, 64, 96])

In [63]:
arr[:8:2]

array([  0,  64, 128, 192])

In [70]:
arr.reshape(8,4,8,1)[:1,1:].flatten()

array([  1,  33,  65,  97, 129, 161, 193, 225,   2,  34,  66,  98, 130,
       162, 194, 226,   3,  35,  67,  99, 131, 163, 195, 227])

In [77]:
arr[[1, 8, 4, 8]].reshape(2,2).transpose()

array([[ 32, 128],
       [  1,   1]])